# -*- coding: utf-8 -*-
"""VacinacaoCovidSC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFCdOcC5OTmf9nIBXonPxnpSGR_sSKsq

Trabalho Final – Parte 2 - Cristopher Braatz Cardoso e Lucas Amaral

* A ideia desse experimento é utilizar o modelo de Malthus para calcular em quanto tempo a população de Santa Catarina estará vacinada do covid19.
* Foi utilizado uma base de dados diários do covid19 no Brasil, com informações de quantidade de vacinados por dia.
* Com essas informações, foi calculado uma média de vacinados por dia, considerando apenas o último mês de vacinação (Abril/21). Essa média foi utilizada como taxa de vacinação.
* Foram feitas iterações, onde cada iteração representa um dia. Foi calculado quantas pessoas estariam vacinadas naquele dia.
* A cada 30 dias, foi feito uma calibragem de 5% no percentual, considerando que a quantidade de vacinas aplicadas sempre vai aumentando.
* Com isso, foi obtido que em 452 dias, toda população de Santa Catarina estará vacinada.
"""

# Bibliotecas necessárias para experimento

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from datetime import datetime  
from datetime import timedelta

# Fazendo leitura de dados de vacinados no Brasil
dados = pd.read_csv("https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv")

# Filtrando apenas o estado de Santa Catarina
dados = dados[dados.state == "SC"]

# Tratamento da data da coleta das informações
dados['date'] = pd.to_datetime(dados['date'])

# Calculando média de vacinados por dia, a partir do mês de Abril de 2021
primeiro_de_abril = datetime(2021, 4, 1)
media_vacinados_por_dia = dados[dados.date > primeiro_de_abril].vaccinated.diff().mean()
print("Media de vacinados por dia =", media_vacinados_por_dia)

# Buscando o total de vacinados até o momento
total_vacinados = dados[dados.date == dados.date.max()].vaccinated.values[0]
print("Total vacinados até o momento =", total_vacinados)

# Estimativa de população de Santa Catarina
populacao_santa_catarina = 7165000
print("População SC =", populacao_santa_catarina)

# Utilizando método de Malthus para calcular quantos dias serão necessários para vacinar a população de SC

# População inicial de vacinados
nova_populacao_vacinada = total_vacinados

# Taxa de vacinação diária
taxa_vacinacao_diaria = media_vacinados_por_dia / populacao_santa_catarina
print("Taxa de vacinação diária =", taxa_vacinacao_diaria * 100, "%")

# Variável para contar os dias necessários
contagem_dias = 1

# Laço de repetição, o código abaixo será executado enquanto a população vacinada for menor que a população total
while nova_populacao_vacinada < populacao_santa_catarina:
  # Calculando a população vacinada no dia, utilizando fórmula de Malthus => P(t) => P0 * e ^ (k*t)
  nova_populacao_vacinada = total_vacinados * np.exp(taxa_vacinacao_diaria * contagem_dias)

  # Calibragem de 5% a cada 30 dias
  if contagem_dias % 30 == 0 :
    print("Dia =",contagem_dias, ";", "População vacinada acumulado =", nova_populacao_vacinada)
    taxa_vacinacao_diaria *= 1.05
    print ("Taxa de vacinação diária calibrada = ", taxa_vacinacao_diaria * 100, "%")

  # Incrementando a quantidade de dias
  contagem_dias += 1

print("Quantidade de dias para vacinar a população de Santa Catarina =", contagem_dias)
print("Estimado para todos os catarinenses estarem vacinados em =", datetime.now() + timedelta(days=contagem_dias))